import type React from "react"
import type { Metadata } from "next"
import { Manrope, Bricolage_Grotesque } from "next/font/google"
import "./globals.css"
import ClientLayout from "./clientLayout"

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
})

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    generator: 'v0.dev'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${manrope.variable} ${bricolage.variable} font-manrope`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  )
}
